name: Hello World
author: Bob Jones
description: Testing the description
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Carlos
outputs:
  time:
    description: "the greeting time"
runs:
  using: "node12"
  main: index.js
