name: Run Docker containers in step

#on: pull_request

on:
  push:
    branches:
      - ${GITHUB_REF}

jobs:
  docker-run-in-steps:
    runs-on: ubuntu-latest
    container:
      image: node:13.7.0-alpine3.11
    steps:
      - name: Check node version
        run: node -v
      - name: Step with Docker - echo entrypoint
        uses: docker://node:8.16.2-alpine3.9
        with:
          entrypoint: /bin/echo
          args: Hello World
      - name: Step with Docker - node entrypoint
        uses: docker://node:8.16.2-alpine3.9
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - name: Pull latest for script.sh copy
        uses: actions/checkout@v2
      - name: Run with script.sh file
        uses: docker://node:13.7.0-alpine3.11
        with:
          entrypoint: ./script.sh
          args: "Some test"
