name: External triggers w/ repository_dispatch

on:
  repository_dispatch:
    types: [myTestEvent]

jobs:
  test-external-event:
    runs-on: ubuntu-latest
    steps:
      - name: Testing repository dispatch functionality
        run: echo "This was triggered by an external event"
      - name: Repository dispatch event payload
        run: echo ${{github.event.client_payload.myTestEnv}}
