name: Setting up node environment matrix

on: create

jobs:
  node-version-matrix:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [8, 10]
        include:
          - os: windows-latest
            node-version: 10
            is-it-node-10-dawg: "Yeah man, it sure is"
    runs-on: ${{ matrix.os }}
    env:
      IS_WINDOWS_NODE_10: ${{ is-it-node-10-dawg }}
    steps:
      - name: Log out current node version
        run: node -v
      - name: Change node version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log out current node version
        run: |
          node -v
          echo $IS_WINDOWS_NODE_10
