name: Simple shell commands

#on: [push, create]
on:
  push:
    branches:
      - master
  create:
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello from my simple shell command action"
      - name: Multiline script
        run: |
          node -v
          npm -v
      - name: Run python command using
        run: |
          import platform
          (platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Uses powershell to print the current directory
        run: Get-Location
      - name: Uses bash to print the current directory
        run: pwd
        shell: bash
